// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8jcmDlN0zVLS98w24Pb43c0GOyXbzcVE',
    appId: '1:244429207550:web:2272c602ef8406b91472af',
    messagingSenderId: '244429207550',
    projectId: 'devshub-week5-app',
    authDomain: 'devshub-week5-app.firebaseapp.com',
    storageBucket: 'devshub-week5-app.firebasestorage.app',
    measurementId: 'G-ENJ18KGZDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7OoJlA8hwvZ1zAQVjbkY8HSKcIRJplE',
    appId: '1:244429207550:android:d6ea23e74e21d3cb1472af',
    messagingSenderId: '244429207550',
    projectId: 'devshub-week5-app',
    storageBucket: 'devshub-week5-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQt3aLIn0_Y-wJipE19izXS3fGPLEIByE',
    appId: '1:244429207550:ios:4c794ac8696158631472af',
    messagingSenderId: '244429207550',
    projectId: 'devshub-week5-app',
    storageBucket: 'devshub-week5-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationAndDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQt3aLIn0_Y-wJipE19izXS3fGPLEIByE',
    appId: '1:244429207550:ios:4c794ac8696158631472af',
    messagingSenderId: '244429207550',
    projectId: 'devshub-week5-app',
    storageBucket: 'devshub-week5-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationAndDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8jcmDlN0zVLS98w24Pb43c0GOyXbzcVE',
    appId: '1:244429207550:web:b7f879c410ffa63b1472af',
    messagingSenderId: '244429207550',
    projectId: 'devshub-week5-app',
    authDomain: 'devshub-week5-app.firebaseapp.com',
    storageBucket: 'devshub-week5-app.firebasestorage.app',
    measurementId: 'G-5BRXG07R7L',
  );
}
